cluster: "sbatch --time={resources.time_min} --mem={resources.mem_mb}
            -c {resources.cpus} -o slurm/logs/{rule}-{wildcards}-%j.out
            -e slurm/logs/{rule}-{wildcards}-%j.out -J smk-{rule}-{wildcards}
            -p interactive_gpu_p --qos=interactive_gpu
            --gres=gpu:{resources.gpu}
            --nice=1000"
jobs: 15
default-resources: [cpus=1, mem_mb=1000, time_min=5, gpu=0]
resources: [cpus=4, mem_mb=16000, gpu=1]
restart-times: 3
scheduler: greedy
printshellcmds: True
keep-going: True

use-conda: True
latency-wait: 60
